#!/bin/bash
echo "=========================================="
echo "Paris Metro Route Finder - Demo"
echo "=========================================="
echo ""

echo "1. Short route (same line):"
echo "   Château de Vincennes → Bastille"
echo ""
./bin/metro_main "Château de Vincennes" "Bastille"
echo ""
echo "----------------------------------------"
echo ""

echo "2. Route with one transfer:"
echo "   Bastille → Opéra"
echo ""
./bin/metro_main "Bastille" "Opéra"
echo ""
echo "----------------------------------------"
echo ""

echo "3. Long route with multiple transfers:"
echo "   Mairie de Montreuil → Pont de Levallois-Bécon"
echo ""
./bin/metro_main "Mairie de Montreuil" "Pont de Levallois-Bécon"
echo ""
echo "=========================================="
echo "Demo complete!"
echo "=========================================="
